version: '3.9'

services:
  nextjs:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - satudata-net
networks:
  satudata-net:
    external: true